# Generated by Django 2.0 on 2018-12-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_remove_courseorg_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='fac_nums',
            new_name='fav_nums',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=29, verbose_name='年龄'),
        ),
    ]
