# Generated by Django 2.0 on 2019-01-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_courseorg_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='fac_nums',
            new_name='fav_nums',
        ),
    ]
