# Generated by Django 2.0 on 2019-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20190102_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '公务员'), ('gr', '事业单位'), ('gx', '军人警察')], default='pxjg', max_length=20, verbose_name='分校类别'),
        ),
    ]
