# Generated by Django 2.0 on 2019-01-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20190105_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_company',
            field=models.CharField(max_length=50, verbose_name='学位'),
        ),
    ]
