# Generated by Django 2.0 on 2018-12-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='申论', max_length=20, verbose_name='课程类别'),
        ),
    ]
