# Generated by Django 2.0 on 2018-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_courseorg_tag'),
        ('courses', '0006_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to='organization.Teacher', verbose_name='讲师'),
        ),
    ]
